language: java
jdk:
- oraclejdk8
notifications:
  irc:
    channels:
      - "chat.freenode.net#hawkular"
    on_success: change
install:
  - mvn -version -B
script:
  - mvn -s .travis.maven.settings.xml verify | grep -vF "[INFO] Downloading:" | grep -vF "[INFO] Downloaded:"; test ${PIPESTATUS[0]} -eq 0
